### ISSUE TITLE
1.18.1 issue

### ISSUE THREAD

**Issue by RatDonkeyGoat** [2mal3/Chunk-Loader-Datapack#2]
not working on 1.18.1 you just despawn the knowledge book when you use it

**Comment by 2mal3** [comment]
The knowledge book is actually just a placeholder when crafting, which should be replaced immediately in the inventory by the correct chunk loader.

That the knowledge book is not immediately deleted from the inventory, can unfortunately have quite a few reasons. But first I would try to uninstall the datapack and then install the newest version.
